### ISSUE TITLE
[의견] TDD 적용

### ISSUE THREAD

**Issue by DalioKim** [ReleaseAppUntilDie/GatheRunner#11]
이번 PR 머지하기전에 테스트케의 논의해보고 TDD 적용해서 검증완료되면 머지하는게 어떨까요?

**Comment by hanjaesueng** [comment]
네 좋습니다 TDD에 대해서 세미나 마치고 같이 논의해보면 좋을거같아요

**Comment by PotatoArtie** [comment]
말씀해주신 방법대로 해도 좋지만, 우선 UI 한것은 머지를 진행하고 
다음 PR 때 각 자 세미나를 내용을 바탕으로 적용해서 코드리뷰를 통해서 더블체킹을 해주는 것도 저는 좋을거 같아요~
