### ISSUE TITLE
EmptyModifier conditions 관련

### ISSUE THREAD

**Issue by wh5929** [ReleaseAppUntilDie/GatheRunner#29]
dalio가 작성한 EmptyModifier 를 코드에 적용하는중입니다.

or, and  조건이 아닐때

none을 선택해서 단일 조건(예: justStartButtonIsSelected == true) 일때 특정 구문이 실행되어야 합니다.

그러나 EmptyModifier 의 conditions은 배열만을 받고 있어 none일때 단일 조건의 상황을 구현할 수 없는 문제가 있습니다.

확인 부탁드립니다.

**Comment by DalioKim** [comment]
배열에 단일 조건을 넣으시면 됩니다. [조건1] 이런 형식으로요.

**Comment by DalioKim** [comment]
설명완료

**Comment by DalioKim** [comment]
단일 조건 추가해서 올리겠습니다.

**Comment by wh5929** [comment]
> 단일 조건 추가해서 올리겠습니다.

확인했습니다. develop 브랜치에 merge되면 RunningView 코드에 적용해보겠습니다.
