### ISSUE TITLE
HeaderView "러닝", "활동" 등의 텍스트가 화면에서 중앙정렬되지 않는 문제

### ISSUE THREAD

**Issue by wh5929** [ReleaseAppUntilDie/GatheRunner#31]
<img width="489" alt="image" src="https://user-images.githubusercontent.com/10336586/184523532-14ed909d-5902-439d-b24b-52c337973b9d.png">

해결 부탁드려요!

**Comment by hanjaesueng** [comment]
수정했습니다 . 다음 PR에 적용하겠습니다~
