### ISSUE TITLE
tabview 구현시 navigationBar hidden 관련

### ISSUE THREAD

**Issue by hanjaesueng** [ReleaseAppUntilDie/GatheRunner#37]
[](url)탭뷰 구현시 navigationView 로 화면이 전환중입니다. 그리고 현재 상단에 navigationbar가 남아 있어서 view들이 전체적으로 밑으로 내려와 있고, 상단에 버튼이 클릭이 불가합니다. 확인 [부탁드립니다.]([url]([url]([url](url)))) 
<img width="398" alt="스크린샷 2022-08-24 오후 7 35 38" src="https://user-images.githubusercontent.com/31721888/186398384-f30e3b2c-57e1-4f66-8abc-5218de7ec133.png">
시뮬레이션에서 실행한 결과
<img width="251" alt="스크린샷 2022-08-24 오후 7 36 16" src="https://user-images.githubusercontent.com/31721888/186398483-6555f824-335f-4b36-86a4-3945d6f0cdbf.png">
캔버스에서 실행한 결과

**Comment by DalioKim** [comment]
네넵 반영하겠습니다.

**Comment by DalioKim** [comment]
조치했습니다.
