### ISSUE TITLE
TabItem+MainComponent 적합여부

### ISSUE THREAD

**Issue by DalioKim** [ReleaseAppUntilDie/GatheRunner#51]
탭뷰의 사용되는아이템의 타입을 정의하는 TabItem에 

네임스페이스 속성으로 MainComponent를 정의 한 후 메인아이템으로 사용을 하고 있는데 MainTabView와 중복되는 느낌이어서 적합한지 의견 부탁드리겠습니다.

**Comment by wh5929** [comment]
음... 전 오히려 있어야 할 곳에 잘 있다는 생각을 합니다.
중복된다고 생각하진 않고 있습니다.
