### ISSUE TITLE
Xcode에서 RunningView의 LocationManager 에서 비롯된 보라색 워닝 발생

### ISSUE THREAD

**Issue by wh5929** [ReleaseAppUntilDie/GatheRunner#66]
### 문제 해결 요청

LocationManager.swift 파일에서 비롯된 문제로 보입니다.

워닝명 -> [SwiftUI] Publishing changes from within view updates is not allowed, this will cause undefined behavior

**Comment by DalioKim** [comment]
https://www.donnywals.com/xcode-14-publishing-changes-from-within-view-updates-is-not-allowed-this-will-cause-undefined-behavior/

**Comment by DalioKim** [comment]
xcode 14의 베타버전에서 발생하는 오류라고하는데 현재 사용하고 계신 xcode의 버전 확인 부탁드립니다.

**Comment by wh5929** [comment]
> xcode 14의 베타버전에서 발생하는 오류라고하는데 현재 사용하고 계신 xcode의 버전 확인 부탁드립니다.

현재 xcode 14.0.1 (14A400) 버전 사용중입니다.
