### ISSUE TITLE
PR 컨벤션 정의

### ISSUE THREAD

**Issue by DalioKim** [ReleaseAppUntilDie/GatheRunner#79]
PR에 대한 규칙이 필요해보입니다. 

각자 레퍼런스 참고해서 대략적인 PR 틀을 짜고 지켜나갈 필요가 있어보입니다.

**Comment by DalioKim** [comment]
제가 참고해서 적용하고 있는 레퍼런스는 다음과 같습니다.

[링크1](https://yungis.dev/github/thought-about-good-pr/)
[링크2](https://xtring-dev.tistory.com/entry/Github-%EC%9E%90%EC%A3%BC-Merge%EB%90%98%EB%8A%94-PR-%EB%A7%8C%EB%93%A4%EA%B8%B0)

실제 대기업 또는 현업과 완전히 똑같이 하자라는 취지가 아닙니다. 일반적으로 사용되고 있는 PR 규칙들에 대해 러프하게 따라가며, 업무습관을 기르자는 취지입니다.  

PR도 커뮤니케이션이고, 협업의 하나입니다. 약속을 정하고 지키지 않으면 의미가 퇴색된다고 생각합니다.

**Comment by hanjaesueng** [comment]
읽오보니 더 작은 단위로 하나의 목표에, 그리고 변화된 내용도 되도록이면 영상까지 첨부해서 PR 올리면 좋을거같습니다. 
 이거에 대해서 한번 얘기를 해봐야할거같습니다.  같이 얘기해서 구체적인 가이드라인을 같이 정하면 좋을거같습니다.
